### ISSUE TITLE
Multiple USB Cameras on high resolution

### ISSUE THREAD

**Issue by rabbie** [ccrisan/motioneye#1034]
I have a pi2 model b with a genuine power supply providing enough power to easily handle the hardware. 

I can have one camera on 1280x720 resolution no problem.

As soon as I increase the resolution of the second camera up to 640x480, the second camera will stop working and only one camera will work.. When I drop the resolution back down again, both cameras work again.

Can anyone else replicate this ?

**Comment by opless** [comment]
Yes, it's because you're exceeding the bandwidth of your USB2 bus, unfortunately you can't do anything about this, other than lowering the capture resolution of the first camera or using the inbuilt camera port for a second camera. 

Though that'll be additional pain getting the onboard camera port to talk v4l2 (there is a solution, historically it's not been terribly stable, YMMV, etc)

**Comment by rabbie** [comment]
Thanks @opless , So the USB Wi-Fi adapter is also on the same bus which I'm going to presume will likely cause issues with reliable connectivity as motionEye is also uploading images on each motion detection event. I'll drop both cameras down to low-ress in order to create a timelapse gallery rather than a high res cctv feed.
