### ISSUE TITLE
Picture and Video have Different  Filenames 

### ISSUE THREAD

**Issue by stefanbollmann** [ccrisan/motioneye#1072]
Uploaded videos and the corresponding images have different file names. So it is difficult to use the images as thumbnails for the videos. Is it possible to get the same file names (except for the extension) by configuration?

**Comment by ccrisan** [comment]
The thumbnails are generated for each video, separately. They have nothing to do with the captured still images. 

Nevertheless, if you want them to have similar names, you have the liberty to change the naming patterns for both movies and still pictures created by motionEye.

**Comment by stefanbollmann** [comment]
Thanks for your quick answer. Can I upload these thumbnails? Or do I have to create the thumbnails on the server? In my current application I need a picture and a video with the same timestamp.

**Comment by grahampowell** [comment]
interestingly, I have just created a crontjob to copy the thumbs from the from the motioneye directory, to my remote directory since they use the SAME name as the video file videoname.thumb. and this works great. would love the option of having these upload to my ftp server as well. or the job being triggered by motion eye on a new video...
