### ISSUE TITLE
[Feature] Google Photo upload

### ISSUE THREAD

**Issue by bob-lee** [ccrisan/motioneye#1212]
Google Photo upload service would be nice as they allow unlimited quota for low resolution media files. I noticed 2 things in the current Google Photo API:

- the API doesn't support deleting a file so `Clean Cloud` is irrelevant
- the API doesn't support sub-album (nested album) so `Include Subfolders` is irrelevant

One possible scenario would be to store all media files in a single album like:

```
MyAlbum
  2019-03-31-15-20-37.mp4
  2019-03-31-23-21-05.mp4
  2019-04-01-03-55-02.mp4
  2019-04-01-12-01-59.mp4
```
@ccrisan Can you please comment?

**Comment by ccrisan** [comment]
@bob-lee let's make sure this is a completely different upload service provider (than the existing Google Drive one). This one would not have *Clean Cloud* feature since it's not available. I don't see a problem in this.

Regarding the *Include Subfolders* options, we should have a way for the provider to specify whether this is available or not. If it's not, we should hide the option, just like we do for the *Clean Cloud* one.

The *Location* option, however, should be used to build the name of the album. Replacing `/` with e.g. `-` should do it.
