### ISSUE TITLE
Grey image after upgrade

### ISSUE THREAD

**Issue by MalFrance** [ccrisan/motioneye#1536]
As motioneye was working well (!) i decided to upgrade from version 0.39 to 0.41.
This is on a Pi3B with Raspbian 8.0, and a Pi camera module.
Following the upgrade, all the previous settings were deleted so spent a little time re-adding the camera and making the other settings.
However, the camera image is not stable and works only for a some seconds after a re-boot, and then changes to show a grey image with the overlay text "unable to open video device since <whenever>" in the top left corner.
Although, occasionally it lasts for a few minutes before i start using it.
Motion was not upgraded during the process and remains at version 4.0.1.
Raspbian updates were installed before i tried the motioneye update, and it was working for about 24 hours until this afternoon. Otherwise, the OS itself wasn't changed from when it was working.

have i missed something somewhere?

Mal

**Comment by zagrim** [comment]
If you had read the release notes for 0.40 you wouldn't have had to re-add the camera (you're not exactly the first one to failing to find those instructions, maybe their presence should be made somehow known to the users): https://github.com/ccrisan/motioneye/releases/tag/0.40
You might want to re-check the current camera config against the old "thread-*.conf" config files in case something changed.

I don't know any sure fix for the gray image, but since Raspbian has package in their repos for Motion, you might want to try to upgrade it from there, anyway. And searching issues (both open and closed, perhaps) for "gray" or "grey" might give you some hints on what to try.
