### ISSUE TITLE
Can't get snapshot url to work in octoprint.

### ISSUE THREAD

**Issue by dfgas** [ccrisan/motioneye#1711]
is there a way to make it to where i don't need any authentication for the snapshot url? If we have it turned off for video it should automatically be off for snapshot as well.

**Comment by Rolleroo** [comment]
I'm having the same issue with this. 

First attempt at snapshot fails, second request for snapshot is successful. I suspect an authentication issue because if I have a browser window logged into Motioneye then snapshots work first time.

Request is being made using the following call:
http://192.168.4.16:8765/picture/1/current/?action=snapshot

Authentication for streaming has been disabled.

Any assistance much appreciated.
