### ISSUE TITLE
Still image is generated after notification is sent

### ISSUE THREAD

**Issue by Akeid** [ccrisan/motioneye#1724]
Hello,

I have noticed that if you have motion notifications enabled with still images enabled, the notification process is called before the still image snapshot is generated. 

I have named my still image generated on a motion event "lastMotionPicture.jpg" via the motioneye gui. Theoretically, every new motion event should replace lastMotionPicture.jpg with the first frame in a new motion event. This process still occurs, but happens after the notification is sent. In my situation, I am using a curl command to send lastMotionPicture.jpg when motion is detected. Due to the sequential logic I described above, I am getting the previous or old "lastMotionPicture.jpg" and not the most recent one.

Would you be able to modify motioneye to invoke a snapshot/still image right before a notification is sent? In my case I am using "Run a command" notification. Thank you

**Comment by zagrim** [comment]
In case of "Run a command", the script is executed at the start of the motion event, that means when motion is first detected. Do you have "Still Images" -> "Capture Mode" set to "Motion Detected" or "Motion Detected (One Image)"? The latter menas the snapshot is likely not available until the end of motion event. You might have better luck if you configured your script to run as "Run An End Command", anyway (since by then the snapshot should in any case be available on disk).

If you wish, you could research this by adding `log_level debug` in my motioneye.conf and then observing the sequence of different events and scripts being run.
