### ISSUE TITLE
Severe video delay

### ISSUE THREAD

**Issue by lilfellabob** [ccrisan/motioneye#1926]
Hi,
I've been running motioneyeos for some time on my raspberry pi 3 without any issues. I've just purchased a new wireless ip cam that has 5mp resolution and added it into the set up. However I'm experiencing severe delay from the video. The camera has it's time displayed in the top right and motioneye overlays the time in the bottom. Comparing the two time stamps shows a difference of around 30 seconds - 1 minute that seems to increase as time goes on. I've turned down the settings on the camera so that the frame rate is as low as 5 FPS, resolution of 800x600 and a bitrate of 512 (other settings were 50 Hz, H264 baseline, variable bit rate). I've also deleted the original camera to try and work out if it's just a matter of the pi's hardware not being powerful enough. Given that none of these things have helped, I'm not sure that this is the pi's fault and I'm hesitant to upgrade to a pi4 if it may not solve the problem.
It's also worth noting that the wifi router is ~1m from the camera for this test set up and it's also interesting that even whilst the new camera is experiencing these issues, the original camera (before I removed it) was functioning properly. 

Any help would be much appreciated!

edit: Opening the video stream in the app or VLC shows the video without issue!

**Comment by darrentaft** [comment]
I'm here for the exact same reason.  It's been about 14 hours since I last restarted motioneye, and my camera is now just over 2 minutes behind live.  I can see it gets stuck on a second every few, which puts it further and further behind.  It was initially set to 720p @ 15fps but it was skipping most frames and getting behind straight away.  I've now set my camera to the very minimum - 5fps @ 640x480 - and it still struggles to keep up.  I have 2 other cameras connected to it running at 720p 15fps, and they're both near-realtime.  All cameras use RTSP.

If it can't keep up, is there a way to get it to catch up with realtime on a frequent basis rather than get further and further behind?
