### ISSUE TITLE
Motioneye only showing Preferences 

### ISSUE THREAD

**Issue by AndyR88** [ccrisan/motioneye#205]
hi
I installed the motioneye image file for raspberry pi 3 (latest version).
I can access the cameras howver it does not provide me with a complete settings menu, only "preferences". See attachment.
How can I access the full setting menu?
Thanks!
![screen shot 2016-05-14 at 20 59 48](https://cloud.githubusercontent.com/assets/4953009/15270406/082f2ff8-1a17-11e6-9823-da64e4611fd1.png)

**Comment by AndyR88** [comment]
I solved it by logging in using username as admin and leaving the password entry empty

**Comment by jjmccl** [comment]
I'm going to add this just because I spent about an hour trying to figure out how to log out/log in, restoring configs by hand etc to try to solve this same problem.  It's dumb of me, but I hope this helps someone else.  Just click the second icon in the top left (the that looks like a  little man).  Phew.
