### ISSUE TITLE
Wrythe Green Surgery

### ISSUE THREAD

**Issue by ronsteenbergen** [ccrisan/motioneye#2103]
Hi there,

Is there a way to set the time in MotionEye when the Pi is not connected to the internet?

**Comment by starbasessd** [comment]
MotionEye, yes in crontab in your base os, you could do ifup/ifdown type commands.
MotionEyeOS, yes, sort of, but involves disabling network watchdog, also, as losing network connectivity causes panic reboots by design.
You can also use Working Schedule to prevent motion detection and notifications, as long as it doesn't cross Midnight.
Some routers/WiFi routers can disable specific ports (ethernet) or device traffic (kid controls) also.

**Comment by starbasessd** [comment]
Yes. You need to console or ssh into the Pi running motionEyeOS and run the command:
date -s "Thu Aug  9 21:31:26 UTC 2012"  << DayofWeek Mon Day 24HourTime TimeZone Year

**Comment by ronsteenbergen** [comment]
thanks, it works
