### ISSUE TITLE
raspberry pi with system default python3

### ISSUE THREAD

**Issue by questrov** [ccrisan/motioneye#2104]
Installed circuit python [https://learn.adafruit.com/circuitpython-on-raspberrypi-linux/installing-circuitpython-on-raspberry-pi](url) which changes system default to python3, which breaks motioneye.  

Bummer since servokit [https://learn.adafruit.com/adafruit-16-channel-servo-driver-with-raspberry-pi/using-the-adafruit-library](url) drives a pwm board nicely with incremental servo control similar to servoblaster which does not seem to work on a Pi4 (works great on zero) along with all the other Adafruit gizmo's.

Does the motioneye python3 fork work on Pi4 yet or is there another workaround?  If so are there any details how to get there from here?  

Tried pip2 on a fresh OS install with circuit python but didn't do something right as the motion service would not start, gave same same error as when I first switched to system default python3...

**Comment by starbasessd** [comment]
Please install motion/motioneye from the github motioneye wiki for either Ubuntu 20.04 or RaspberryPiOS. That will install the correct pip2. You will have to do python2 and pip2  commands for motion/motioneye or set default to python2 and call circuit python with python3 commands.

On April 20, 2021, at 9:33 PM, questrov ***@***.***> wrote:

Installed circuit python https://learn.adafruit.com/circuitpython-on-raspberrypi-linux/installing-circuitpython-on-raspberry-pi which changes system default to python3, which breaks motioneye.

Bummer since servokit https://learn.adafruit.com/adafruit-16-channel-servo-driver-with-raspberry-pi/using-the-adafruit-library drives a pwm board nicely with incremental servo control similar to servoblaster which does not seem to work on a Pi4 (works great on zero) along with all the other Adafruit gizmo's.

Does the motioneye python3 fork work on Pi4 yet or is there another workaround? If so are there any details how to get there from here?

Tried pip2 on a fresh OS install with circuit python but didn't do something right as the motion service would not start, gave same same error as when I first switched to system default python3...

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.￼

[ { ***@***.***": "<a href="http://schema.org">http://schema.org</a>", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "<a href="https://github.com/ccrisan/motioneye/issues/2104">https://github.com/ccrisan/motioneye/issues/2104</a>", "url": "<a href="https://github.com/ccrisan/motioneye/issues/2104">https://github.com/ccrisan/motioneye/issues/2104</a>", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } } ]

**Comment by questrov** [comment]
Sorted thank you very much!
