### ISSUE TITLE
Can't upload any images when the IP automatically change after

### ISSUE THREAD

**Issue by eddy131415** [ccrisan/motioneye#2128]
I can't received any pics when the IP automatically changed, than I tried to re-stall the .img and set the static IP or wifi private IP, but it didn't uploaded too, Accessing the upload service failed.
where's the problems?have anybody can help me?

**Comment by starbasessd** [comment]
Are you using motionEye or motionEyeOS?
If motioneye, what is your base OS and what hardware/PC?
If motionEyeOS, which version, on what hardware?
How are you entering the IP address? 
Can you ping the IP address or view the WebGUI when set to the static IP?

Please answer ALL the questions in order to be able to help you better.

**Comment by eddy131415** [comment]
Hello, thanks for your reply. I'm using motionEyeOS with raspberry pi 4.
The motionEyeOS version that I using is dev20201026.I tried to use the
cable network(have set up the static IP) and wireless but it didn't work
either. If any questions can't understand, please reply me.

Thanks a lot !

starbasessd ***@***.***> 於 2021年5月23日 週日 下午7:11寫道：

**Comment by starbasessd** [comment]
Can you ping the IP address or view the WebGUI when set to the static IP?

**Comment by starbasessd** [comment]
Sorry, clicked the wrong button. It's re-opened.

Can you ping the IP address or view the WebGUI when set to the static IP?

**Comment by eddy131415** [comment]
Thanks for your reply. I try to release the 4 webcam and set the upload
step by step,they can work now!

Thanks a lot!!!!!

starbasessd ***@***.***> 於 2021年5月23日 週日 下午8:52寫道：
