### ISSUE TITLE
Network Share Option not offered

### ISSUE THREAD

**Issue by vtrack** [ccrisan/motioneye#244]
Hi,
I just installed the latest version of motioneye on raspbian, following the instructions in the wiki.
0.32.2
Linux raspberrypi 4.4.14+ #896 Sat Jul 2 14:16:46 BST 2016 armv6l GNU/Linux

compiled latest trunk of motion
ffmpeg from your pre-compiled url.

I am not seeing the option to save files to a network share in the dropdown. in File Storage/Storage Device. I only see "Custom Path" or SL16G with a path to a local device.
See attached configs.

[motioneye.txt](https://github.com/ccrisan/motioneye/files/350468/motioneye.txt)
[thread-1.txt](https://github.com/ccrisan/motioneye/files/350469/thread-1.txt)

**Comment by vtrack** [comment]
still researching this. Is this something with the motioneye feature-set? I am coming from MotionPie and was hoping to have more or less the same features. If not, I would use motionos, but I need the ability to add repos and use the gpio.

**Comment by ccrisan** [comment]
Set [smb_shares](https://github.com/ccrisan/motioneye/wiki/Configuration-File#smb_shares) setting (in motioneye.conf) to `true`.

**Comment by stjowa-gn** [comment]
When I set to true the service will not start.

**Comment by jasonhpchu** [comment]
After tinkering for a while, I've found the issue that none of the logs told me.
running this directly, it gave me the log on the stream, which told me the problem:
 /usr/local/bin/meyectl startserver -c /etc/motioneye/motioneye.conf

it'll say CRITICAL: please install cifs-utils
now, going to edit the server script to have it log to file

**Comment by MarcoMirisola** [comment]
Hi, I think that @jasonhpchu solutions should be added in the installation guide!

**Comment by Frank-Ov** [comment]
Hello

i have a similar problem.
3 cameras attached on MotionEye ( Debian ) - two Raspi  ( "0" and PI3 ) and one Instar IN-3011cam. 
Everything works fine - thank you for the great work.
Just missing the option "File Storage - Network Share " on the Instar cam. Its working on both PI´s perfectly. Local storage is available

 and working cam is working pretty well.
Is it because of the Instar  cam ?? 
![2020-01-09 11_42_15-NAS04-MotionEye](https://user-images.githubusercontent.com/59473646/72060940-36617180-32d5-11ea-9728-ba267935316c.png)
Thank you for help !
Grüße
Frank

**Comment by fgtome** [comment]
Hi guys, so I am having the same problem here.

I'm running Motion Eye over Debian 12 in arm64 (on my Raspberry Pi 4). Because I did not have the network share option on any camera, I changed the smb_shares to true, and after rebooting, I lost access to the GUI.

Can someone help me fix this, please? I still have access to it via SSH, though.

Both cameras are built with Raspberry Pi Zero W running motioneyeOS in "Fast Camera Mode".

Thank you all!
