### ISSUE TITLE
What folder?

### ISSUE THREAD

**Issue by donde321** [ccrisan/motioneye#527]
Where do I put the wpa_supplicant.conf file?
I've read in /data, /etc,  /boot, and a couple more folders!
And what should it look like?

**Comment by ccrisan** [comment]
I'm assuming this is about motionEyeOS, not motionEye.

**Before** the first boot, the most convenient way is to place it on the boot partition, since it's accessible from any Windows machine.

If you have already booted your motionEyeOS, you'll need to place it in /data/etc. For more details, see https://github.com/ccrisan/motioneyeos/wiki/Tweaks#manually-editing-network-configuration
