### ISSUE TITLE
[Feature Request] Sync instead of upload to DropBox

### ISSUE THREAD

**Issue by chrisf4lc0n** [ccrisan/motioneye#634]
At the moment I am using DropBox Headless Client to sync image folders from my MotionEye Ubuntu Server to DropBox. On the Server side MotionEye only stores the images for 14 days, when using the built-in upload feature old folders (over 14 days old) do not get deleted on the DropBox side.
Any chance of introducing a sync feature instead of plain upload?

**Comment by ccrisan** [comment]
Given the many cases where users' personal photos have been deleted by motionEye just because they set a too broad root folder for their motionEye camera, I won't be implementing any (more) removals of users' files. Especially not on Dropbox or Google Drive. Folder synchronization agents/daemons already exist for most major cloud providers, so if a synchronization is desired between local folders and the cloud, this should be done outside motionEye.
