### ISSUE TITLE
Running 0.36.1 will not find update 0.37

### ISSUE THREAD

**Issue by raymate** [ccrisan/motioneye#648]
Just set up a fresh new camera

My current camera that has been running for almost a year is on 0.36.1

Was trying to add the second camera got error, then worked out the new fresh camera is running 0.37, so went back to my older camera and hit update, it says its up to date.

It can't find new update.

Od course I could simply pull down the old camera and flash a new system to it, but it's installed in a place that needs a ladder and its a pain to access.

Any reason why it can't find the update?

**Comment by ccrisan** [comment]
I assume you refer to motionEyeOS rather than just motionEye. If that's the case, see https://github.com/ccrisan/motioneyeos/wiki/FAQ#i-noticed-a-new-version-has-been-released-why-does-my-motioneyeos-say-its-up-to-date.

In any case, if your system is relatively inaccessible, I don't recommend updating it unless you'll benefit from one of the new features/bug fixes. Keep in mind that 20170827 is a *prerelease*.
