### ISSUE TITLE
Network camera, no drop down menu

### ISSUE THREAD

**Issue by mwjcp** [ccrisan/motioneye#727]
Hi,

I've installed motioneyeos on a raspi3 using the motioneyeos-raspberrypi3-20171008.img.gz image. 

When I try to install a network camera I don't get a drop down menu for the last option "Camera" and I can't click "ok" without selecting a camera type.

Additionally when I ssh in to the machine the command line does not have commands like "wget" or "apt" for me to futz with the problem.

I have tried downloading the image and installing it a couple of different times.

Thanks,
Matthew

![screenshot from 2017-11-29 20 42 27](https://user-images.githubusercontent.com/34115598/33410519-438d1a7e-d546-11e7-9e12-9603f8eb7a1a.png)

**Comment by ccrisan** [comment]
You don't have a camera dropdown because you entered an invalid ip address ("ip address" is not a valid address - you should hover the red exclam sign).

You don't have wget or apt because: https://github.com/ccrisan/motioneyeos/wiki/FAQ#i-cant-seem-to-find-apt-get-or-any-other-package-manager-what-gives
