### ISSUE TITLE
Non Network Connected USB Swappable

### ISSUE THREAD

**Issue by FuzzyKaos** [ccrisan/motioneye#949]
Hi, I am interested in using your project for a remote location with out access to internet.
What I would like to do is to when required go to the motioneye camera pull out a USB stick containing any media that the camera created and pop in another USB stick to continue with the recording.

So far this seems like an impossible task without having to log into the raspberry pi and fiddle with the settings.

Is this possible using the method that I prefer or is there another way around it, maybe using a second pi or such.

If this were a windows device, pulling out the thumb drive (D:) and replacing it with another would also give it the drive letter of D:.

As it is now, if I plug in a usb stick called USB, when I put in the second it calls it USB1 and so forth.

**Comment by ccrisan** [comment]
This is something that is specific to Linux and has nothing to do with motionEye. In any case, you should definitely unmount your drive before pulling it out, be it Windows or Linux. Otherwise chances are that you'll be left with partial (corrupted) media files or even corrupted filesystem on your drive.
