### ISSUE TITLE
Camera seems to be constantly reconnectiong

### ISSUE THREAD

**Issue by KarlBaumann** [ccrisan/motioneye#996]
Any idea what could be causing this? 
https://www.youtube.com/watch?v=C7ke156OjUQ

**Comment by ccrisan** [comment]
That looks to me like a hardware or camera fault. You didn't provide any details about your system, but what I can clearly say about your problem is that it's not a Motion nor a motionEye problem. If it were, you would see a *no-camera* icon every now and then instead of your stream. What you're seeing is an uninterrupted stream which sometimes lacks actual video information. I can't help you anymore than this with your problem.
